"""Navigation module: Telegram screen state machine + stable callbacks."""

from cloud_platform.modules.navigation.domain import (
    CALLBACK_VERSION,
    DONE,
    ENTRIES,
    MAIN,
    Callback,
    CallbackError,
    InvalidNavigationTransition,
    NavAction,
    NavScreen,
    UnknownFlowError,
    all_screens,
    can_back,
    can_cancel,
    decode_callback,
    encode_callback,
    start_flow,
    transition,
)

__all__ = [
    "CALLBACK_VERSION",
    "DONE",
    "ENTRIES",
    "MAIN",
    "Callback",
    "CallbackError",
    "InvalidNavigationTransition",
    "NavAction",
    "NavScreen",
    "UnknownFlowError",
    "all_screens",
    "can_back",
    "can_cancel",
    "decode_callback",
    "encode_callback",
    "start_flow",
    "transition",
]
